
FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y ffmpeg dos2unix

WORKDIR /app

COPY /batchProcessing/videoProcessing.sh /app/videoProcessing.sh

COPY /batchProcessing/idrl.jpg  /app/idrl.jpg

RUN chmod +x /app/videoProcessing.sh

RUN dos2unix /app/videoProcessing.sh

RUN mkdir -p /app/videos

RUN chmod 777 /app/videos


ENTRYPOINT ["/bin/bash","./videoProcessing.sh"]

